---

# This workflow will install Python dependencies and lint with a single version of Python
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run pre-commit quality check

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  run-precommit:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache venv
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: ${{ env.pythonLocation }}
          key: cache-venv-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: cache-venv-

      - name: Cache precommit
        uses: actions/cache@v4
        id: cache-precommit
        with:
          path: ~/.cache/pre-commit
          key: cache-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: cache-precommit-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[lint]
          python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Run precommit
        run: SKIP=no-commit-to-branch pre-commit run --all-files
